version: '3'

services:
  kafka-server:
    image: confluentinc/cp-kafka:6.2.0
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_CREATE_TOPICS=test-topic:1:1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_LOG_RETENTION_HOURS=168
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    ports:
      - "9090:2181"
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "9080:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: true
