version: "3"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: "dbname"
      MYSQL_ROOT_PASSWORD: "Hit@2024"
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql: