server:
  port: 8080
  socket:
    host: 0.0.0.0
    port: 9200
spring:
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

app:
  security:
    server-key: Hotel@2024
    jwt:
      secret-key: 52344E62DC399D1A15AC51A65F1DE
      access-expire: 1440
      refresh-expire: 60
  external-cache:
    enable: true
    application-cache: HOTEL-SOCKET
    delimiter: '::'
    cache-default-expire: 864000
    cache-expirations:
      example-cache: 3600
    redisson:
      single-server-config:
        address: redis://localhost:6379
        idle-connection-timeout: 10000
        connect-timeout: 30000
        timeout: 30000
        retry-attempts: 3
        retry-interval: 1500
        subscriptions-per-connection: 5
        client-name:
        keep-alive: false
        tcp-no-delay: false
logging:
  level:
    com.hit: debug
