version: '3.8'

services:
  redis:
    image: redis:7
    container_name: si-redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass Hit@2024
    volumes:
      - redis_data:/data
      - redis_conf:/usr/local/etc/redis
  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: si-redis-insight
    ports:
      - "5540:5540"
    volumes:
      - redis-insight:/data
volumes:
  redis_data:
  redis_conf:
  redis-insight:
